/**
 * google-fonts.d.ts
 * This file contains a curated selection of top Google font families as TypeScript types.
 * https://fonts.google.com/
 * Created by Jared Truscott and chatGPT
 * 'There probably was a better way to do this'
 */

//cspell:disable
export type GoogleFontFamily =
	| "Abril Fatface"
	| "Acme"
	| "Adamina"
	| "Alegreya"
	| "Alegreya Sans"
	| "Alegreya Sans SC"
	| "Alef"
	| "Alice"
	| "Alata"
	| "Almarai"
	| "Amaranth"
	| "Amatic SC"
	| "Amiri"
	| "Andika"
	| "Anton"
	| "Archivo"
	| "Archivo Narrow"
	| "Arimo"
	| "Asap"
	| "Asar"
	| "Assistant"
	| "Athiti"
	| "Azeret Mono"
	| "Bai Jamjuree"
	| "Baloo"
	| "Baloo 2"
	| "Baloo Chettan 2"
	| "Balsamiq Sans"
	| "Bangers"
	| "Barlow"
	| "Barlow Condensed"
	| "Barlow Semi Condensed"
	| "Bebas Neue"
	| "BenchNine"
	| "Bitter"
	| "Black Han Sans"
	| "Boogaloo"
	| "Bree Serif"
	| "Bubblegum Sans"
	| "Bungee"
	| "Bungee Inline"
	| "Cairo"
	| "Cabin"
	| "Cabin Condensed"
	| "Candal"
	| "Cardo"
	| "Carme"
	| "Carrois Gothic SC"
	| "Catamaran"
	| "Caveat"
	| "Caudex"
	| "Caveat"
	| "Cherry Cream Soda"
	| "Chivo"
	| "Cormorant"
	| "Cormorant Garamond"
	| "Cormorant SC"
	| "Coustard"
	| "Crimson Pro"
	| "Crimson Text"
	| "Crete Round"
	| "Creepster"
	| "Cuprum"
	| "Cutive Mono"
	| "DM Mono"
	| "DM Sans"
	| "Dancing Script"
	| "Didact Gothic"
	| "Dosis"
	| "Domine"
	| "Economica"
	| "Encode Sans"
	| "Encode Sans Expanded"
	| "Eczar"
	| "El Messiri"
	| "Exo"
	| "Exo 2"
	| "Expletus Sans"
	| "Faustina"
	| "Farro"
	| "Fira Code"
	| "Fira Sans"
	| "Fira Sans Extra Condensed"
	| "Fjalla One"
	| "Forum"
	| "Frank Ruhl Libre"
	| "Gloria Hallelujah"
	| "Glegoo"
	| "Gochi Hand"
	| "Gothic A1"
	| "Great Vibes"
	| "Grenze Gotisch"
	| "Heebo"
	| "Hepta Slab"
	| "Hind"
	| "Hind Guntur"
	| "Hind Siliguri"
	| "Hind Vadodara"
	| "Hammersmith One"
	| "IBM Plex Mono"
	| "IBM Plex Sans"
	| "IBM Plex Sans Arabic"
	| "IBM Plex Sans KR"
	| "Inconsolata"
	| "Indie Flower"
	| "Itim"
	| "Josefin Sans"
	| "Jost"
	| "Julius Sans One"
	| "Kanit"
	| "Karla"
	| "Karma"
	| "Khand"
	| "Kreon"
	| "Krona One"
	| "Lexend Deca"
	| "Lexend Exa"
	| "Lexend Giga"
	| "Lexend Tera"
	| "Libre Baskerville"
	| "Libre Franklin"
	| "Limelight"
	| "Lobster"
	| "Lora"
	| "Lato"
	| "Luckiest Guy"
	| "Mada"
	| "Major Mono Display"
	| "Magra"
	| "Manrope"
	| "Marck Script"
	| "Martel"
	| "Martel Sans"
	| "Maven Pro"
	| "Merriweather"
	| "Merriweather Sans"
	| "Merienda"
	| "Mitr"
	| "Mochiy Pop One"
	| "Mochiy Pop P One"
	| "Monda"
	| "Montserrat"
	| "Mukta"
	| "Muli"
	| "Nanum Gothic"
	| "Nanum Myeongjo"
	| "Nanum Pen Script"
	| "Neuton"
	| "Niramit"
	| "Noticia Text"
	| "Noto Sans"
	| "Noto Sans Hebrew"
	| "Noto Sans JP"
	| "Noto Sans KR"
	| "Noto Serif"
	| "Noto Serif Display"
	| "Noto Serif JP"
	| "Nunito"
	| "Nunito Sans"
	| "Open Sans"
	| "Oswald"
	| "Overpass"
	| "Overpass Mono"
	| "Oxygen"
	| "Pacifico"
	| "Padauk"
	| "Parisienne"
	| "Passion One"
	| "Patua One"
	| "Permanent Marker"
	| "Philosopher"
	| "Piazzolla"
	| "Play"
	| "Playfair Display"
	| "Playfair Display SC"
	| "Poiret One"
	| "Poppins"
	| "Prata"
	| "Proza Libre"
	| "PT Sans"
	| "PT Serif"
	| "Public Sans"
	| "Quattrocento"
	| "Quattrocento Sans"
	| "Questrial"
	| "Quicksand"
	| "Raleway"
	| "Rambla"
	| "Red Hat Display"
	| "Red Rose"
	| "Recursive"
	| "Righteous"
	| "Rokkitt"
	| "Roboto"
	| "Roboto Condensed"
	| "Roboto Slab"
	| "Rufina"
	| "Rubik"
	| "Ruslan Display"
	| "Russo One"
	| "Rozha One"
	| "Saira"
	| "Saira Condensed"
	| "Saira Semi Condensed"
	| "Sanchez"
	| "Sarabun"
	| "Sansita"
	| "Satisfy"
	| "Scope One"
	| "Secular One"
	| "Sen"
	| "Shanti"
	| "Shrikhand"
	| "Signika"
	| "Slabo 13px"
	| "Slabo 27px"
	| "Source Sans Pro"
	| "Source Serif Pro"
	| "SUSE"
	| "Space Mono"
	| "Spectral"
	| "Spectral SC"
	| "Sriracha"
	| "Staatliches"
	| "Stint Ultra Condensed"
	| "Tajawal"
	| "Tangerine"
	| "Teko"
	| "Tenali Ramakrishna"
	| "Tinos"
	| "Titillium Web"
	| "Tourney"
	| "Trirong"
	| "Ubuntu"
	| "Varela Round"
	| "Vollkorn"
	| "Vollkorn SC"
	| "Work Sans"
	| "Yantramanav"
	| "Yellowtail"
	| "Yeseva One"
	| "Yrsa"
	| "Zilla Slab";
